name: Build and Test aos

on: [push, workflow_dispatch, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        step: [build:aos, test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - run: yarn --frozen-lockfile --ignore-engines
      - run: yarn ${{ matrix.step }}
